name: Build Tcl/Tk
on:
  push:
  workflow_dispatch:

env:
  TCL_TK_VERSION: "9.0.2"
  TCL_TK_BRANCH: "core-9-0-2"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: |
            git
            mingw-w64-x86_64-toolchain
            make
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-minizip

      - name: Clone Tcl and Tk
        run: |
          git clone --depth 1 --branch ${{ env.TCL_TK_BRANCH }} https://github.com/tcltk/tcl.git
          git clone --depth 1 --branch ${{ env.TCL_TK_BRANCH }} https://github.com/tcltk/tk.git

      - name: Debug - Check directory structure
        run: |
          pwd
          ls -la
          ls -la tcl/win || echo "tcl/win not found"
          ls -la tk/win || echo "tk/win not found"

      - name: Build Tcl
        run: |
          cd tcl/win
          ./configure --enable-64bit --disable-zipfs --prefix=$HOME/dist
          make -j4
          make install

      - name: Build Tk
        run: |
          cd tk/win
          ./configure --enable-64bit --disable-zipfs --with-tcl=$HOME/dist/lib --prefix=$HOME/dist
          make -j4
          make install

      - name: Set padded build number
        run: |
          echo "PADDED_BUILD=$(printf '%04d' ${{ github.run_number }})" >> $GITHUB_ENV

      - name: Package Results
        run: |
          tar -czf tcl-tk-${{ env.TCL_TK_VERSION }}-build${{ env.PADDED_BUILD }}-win64.tar.gz -C $HOME dist/

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: tcl-tk-${{ env.TCL_TK_VERSION }}-build${{ env.PADDED_BUILD }}-win64
          path: tcl-tk-${{ env.TCL_TK_VERSION }}-build${{ env.PADDED_BUILD }}-win64.tar.gz

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: tcl-tk-${{ env.TCL_TK_VERSION }}-build${{ env.PADDED_BUILD }}-win64.tar.gz
          tag_name: ${{ env.TCL_TK_VERSION }}-build-${{ env.PADDED_BUILD }}
          name: Tcl/Tk ${{ env.TCL_TK_VERSION }} Build ${{ env.PADDED_BUILD }}
          body: |
            Automated build of Tcl/Tk ${{ env.TCL_TK_VERSION }} for Windows x64

            Built with MinGW-w64 on MSYS2
            Build number: ${{ env.PADDED_BUILD }}
            Commit: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}